MaxEventSize: 0 # value 0 unlimit the maximum event size that can be sent to message bus or core-data
Writable:
  LogLevel: INFO

# # uncomment when running from command-line in hybrid mode with -cp -o flags
#Registry:
# Host: localhost
#
#Clients:
# core-metadata:
#   Host: localhost # uncomment when running from command-line in hybrid mode

Service:
  Host: core-metadata.edgex.ziti
  Port: 80
  StartupMsg: device virtual started
  ListenMode: "zerotrust"
  ListenOptions:
    OpenZitiController: "ec2-3-134-108-218.us-east-2.compute.amazonaws.com:8441"
    OpenZitiServiceName: "edgex.device-virtual"

MessageBus:
#  Host: localhost # uncomment when running from command-line in hybrid mode
  Optional:
    ClientId: device-virtual

Device:
  # These have common values (currently), but must be here for service local env overrides to apply when customized
  ProfilesDir: "./res/profiles"
  DevicesDir: "./res/devices"

Clients:
  core-metadata:
    Protocol: http
    Host: core-metadata.edgex.ziti
    #Port: 59881
    Port: 80
    SecurityOptions:
      Mode: "zerotrust"
      OpenZitiController: "ec2-3-134-108-218.us-east-2.compute.amazonaws.com:8441"
      OpenZitiServiceName: "core-metadata"
